### ISSUE TITLE
Incorporate fail0verflow's PS3 tools to decrypt/encrypt PS3 EBOOTs

### ISSUE THREAD

**Issue by 505e06b2** [LBPUnion/UnionRemotePatcher#1]
**Positives**
* Able to automate the entire patching process
* Possibility of automating the entire process if the console were to enable an FTP server
* Possibility of the user not needing to download any software (could be hosted as a web page and operated via the PS3)
* More user-friendly

**Negatives:**
* May be a legal concern, but the source code is available and was written from scratch as far as I know (GPL2)
* Introducing unsafe code into the project
* Assemblies would need to be compiled per-platform
* May need to alter the original C source for better usability
* Will not work for Vita

Thoughts?

**Comment by AShifter** [comment]
Solved in 064a8f6
